mod add_pane;
mod file_browser_pane;
mod frame_edit_pane;
mod help_pane;
mod home_pane;
mod mixer_pane;
mod piano_roll_pane;
mod sequencer_pane;
mod server_pane;
mod instrument_edit_pane;
mod instrument_pane;
mod sample_chopper_pane;

pub use add_pane::AddPane;
pub use file_browser_pane::FileBrowserPane;
pub use frame_edit_pane::FrameEditPane;
pub use help_pane::HelpPane;
pub use home_pane::HomePane;
pub use mixer_pane::MixerPane;
pub use piano_roll_pane::PianoRollPane;
pub use sequencer_pane::SequencerPane;
pub use server_pane::ServerPane;
pub use instrument_edit_pane::InstrumentEditPane;
pub use instrument_pane::InstrumentPane;
pub use sample_chopper_pane::SampleChopperPane;
